services:
  postgres:
    image: postgres:17.7-alpine3.22
    container_name: projecta-postgres
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: projecta
    ports:
      - "5432:5432"